saia/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= "saia"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('creaturl', views.creaturl ,name='creaturl'),
    path('creaturl/send', views.send , name='send'),
    path('s/<str:short>',views.short, name='short'),
    path('do', views.do, name='do'),
 ]

smart/urls.py
from django.contrib import admin
from django.urls import path , include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('saia.urls')),
]

saia/models.py
from django.db import models

# Create your models here.

class mysaia(models.Model):
    port1 = models.CharField(max_length= 1000)
    port2 = models.CharField(max_length= 1000)
    export = models.CharField(max_length= 1000)
    

saia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import mysaia
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
# Create your views here.

def creaturl(request):
    return render(request, 'saia/myurl.html',{})
    
def send(request):
    return render(request, 'saia/myurl.html',{})
    
    
def do(request):
    port1=request.POST.getlist("portal1")[0]
    port2=request.POST.getlist("portal2")[0]
    external = mysaia()
    external.port1 = port1
    external.port2 = port2
    external.save()
    contex = {
           'portal' : external,  
    
    }
    return render(request, 'saia/done.html',contex)
    
    

def short(request, short):
    url = get_object_or_404(mysaia, port2=short)
    print(url.port1)
    return redirect(url.port1)

saia/templates/saia/done.html
<!DOCTYPE html>
<html>
	<body>
		<a href="http://127.0.0.1:8000/s/{{ portal.port2 }}">http://127.0.0.1:8000/s/{{ portal.port2 }}</a>
	</body>
</html>

saia/templates/saia/myurl.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="direction: rtl;">
<div> 
    <form action={% url "saia:do" %} method="post" style="margin-right: 450px;margin-top: 200px;">
        {% csrf_token %}
            <label for="port1" style="color: black;direction: rtl;">لینک طولانی اولیه خود را وارد کنید:</label><br>
            <input type="text" name="portal1" id="port1"><br><br>
            <label for="port2" style="color: black;">ادرس لینک کوتاه شده خود را بنویسید </label><br>
            <input type="text" name="portal2" id="port2"><br><br>
            
            <input type="submit" value="بزن  بریم" style="width: 100px;height: 40px;">
        </form>
</div> 




</div>


</body>
</html>